repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
